name: test_dio
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # StateManagement & DI
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1

  #dio
  dio: ^5.4.2+1

  #utils
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  very_good_analysis: ^5.1.0
  riverpod_lint: ^2.3.10

  # Code gen
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  
flutter:
  uses-material-design: true


